import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import styles from '@/styles/Home.module.css';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
    return (
        <>
            <Head>
                <title>Grim Movies</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <h1>Hello World</h1>
            console.log(  const confirmAdd = () => {
        form.validateFields().then((values) => {
            axios
                .post(
                    `https://localhost:44311/api/services/app/Movie/Create/`,
                    values
                )
                .then((res) => {
                    const newMovie: Movie = res.data.result;
                    setMovies((prevMovies) => [...prevMovies, newMovie]);
                    setAddModalVisible(false);
                })
                .catch((error) => console.error(error));
        });
    };)
        </>
    );
}
